rules:
  - host: "localhost"
  - path: "/api/v1/:type"
  - to:
    - host: "localhost:3001"
    - path: "/api/:type"
    - headers:
      - "X-HP-A": "hello"
      - "X-HP-B": "world"

  - host: "localhost:3001"
  - path: "/api/*"
  - to:
    - type: "origin"
  - headers:
    - "X-HP": "true"
